### ISSUE TITLE
Query params without values throw NPE

### ISSUE THREAD

**Issue by ofields** [DinoChiesa/Apigee-Java-AWSV4-Signature#3]
Code expects every param to have a value, which isn't a requirement. e.g. "test.com/foo?1" will trigger this error whereas "test.com/foo?1=1" works as expected

`java.lang.NullPointerException at java.net.URLEncoder.encode(URLEncoder.java:204) at com.google.apigee.callouts.AWSV4Signature.encodeURIComponent(AWSV4Signature.java:134) at com.google.apigee.callouts.AWSV4Signature$SignConfiguration.<init>(AWSV4Signature.java:287) at com.google.apigee.callouts.AWSV4Signature.execute(AWSV4Signature.java:425) at com.apigee.steps.javacallout.JavaCalloutStepDefinition$ClassLoadWrappedExecution.execute(JavaCalloutStepDefinition.java:235) `

**Comment by DinoChiesa** [comment]
ok thanks for that report.

**Comment by DinoChiesa** [comment]
This is now fixed.
